language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - yarn

install:
  - yarn test

after_success:
  - yarn release
